/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-31 at 16:50:48 UTC 
 * Modify at your own risk.
 */

package com.appspot.mythic_altar_759.server_api.model;

/**
 * Model definition for ApiMessagesQueryResponseMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the server_api. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiMessagesQueryResponseMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("near_friends")
  private java.util.List<ApiMessagesFriendLocation> nearFriends;

  static {
    // hack to force ProGuard to consider ApiMessagesFriendLocation used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(ApiMessagesFriendLocation.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ApiMessagesFriendLocation> getNearFriends() {
    return nearFriends;
  }

  /**
   * @param nearFriends nearFriends or {@code null} for none
   */
  public ApiMessagesQueryResponseMessage setNearFriends(java.util.List<ApiMessagesFriendLocation> nearFriends) {
    this.nearFriends = nearFriends;
    return this;
  }

  @Override
  public ApiMessagesQueryResponseMessage set(String fieldName, Object value) {
    return (ApiMessagesQueryResponseMessage) super.set(fieldName, value);
  }

  @Override
  public ApiMessagesQueryResponseMessage clone() {
    return (ApiMessagesQueryResponseMessage) super.clone();
  }

}
