application: mythic-altar-759
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
# Used for serving APIs
- name: endpoints
  version: latest

# Used for OAuth2 and APIs that wish to authenticate users
- name: pycrypto
  version: latest

handlers:
  # Static content
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

  # Dynamic content
- url: /_ah/spi/.*
  script: api.server.APPLICATION

