application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images

- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /crons/summary
  script: cron.cronapp
  login: admin

- url: /.*
  script: main.app

