/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-31 at 16:50:48 UTC 
 * Modify at your own risk.
 */

package com.appspot.mythic_altar_759.server_api;

/**
 * Service definition for ServerApi (v1).
 *
 * <p>
 * ==== MeetUp Service API ====
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ServerApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ServerApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.19.0 of the server_api library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://mythic-altar-759.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "server_api/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public ServerApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  ServerApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "query_near_friends".
   *
   * This request holds the parameters needed by the server_api server.  After setting any optional
   * parameters, call the {@link QueryNearFriends#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.mythic_altar_759.server_api.model.ApiMessagesQueryRequestMessage}
   * @return the request
   */
  public QueryNearFriends queryNearFriends(com.appspot.mythic_altar_759.server_api.model.ApiMessagesQueryRequestMessage content) throws java.io.IOException {
    QueryNearFriends result = new QueryNearFriends(content);
    initialize(result);
    return result;
  }

  public class QueryNearFriends extends ServerApiRequest<com.appspot.mythic_altar_759.server_api.model.ApiMessagesQueryResponseMessage> {

    private static final String REST_PATH = "query";

    /**
     * Create a request for the method "query_near_friends".
     *
     * This request holds the parameters needed by the the server_api server.  After setting any
     * optional parameters, call the {@link QueryNearFriends#execute()} method to invoke the remote
     * operation. <p> {@link QueryNearFriends#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.mythic_altar_759.server_api.model.ApiMessagesQueryRequestMessage}
     * @since 1.13
     */
    protected QueryNearFriends(com.appspot.mythic_altar_759.server_api.model.ApiMessagesQueryRequestMessage content) {
      super(ServerApi.this, "POST", REST_PATH, content, com.appspot.mythic_altar_759.server_api.model.ApiMessagesQueryResponseMessage.class);
    }

    @Override
    public QueryNearFriends setAlt(java.lang.String alt) {
      return (QueryNearFriends) super.setAlt(alt);
    }

    @Override
    public QueryNearFriends setFields(java.lang.String fields) {
      return (QueryNearFriends) super.setFields(fields);
    }

    @Override
    public QueryNearFriends setKey(java.lang.String key) {
      return (QueryNearFriends) super.setKey(key);
    }

    @Override
    public QueryNearFriends setOauthToken(java.lang.String oauthToken) {
      return (QueryNearFriends) super.setOauthToken(oauthToken);
    }

    @Override
    public QueryNearFriends setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QueryNearFriends) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QueryNearFriends setQuotaUser(java.lang.String quotaUser) {
      return (QueryNearFriends) super.setQuotaUser(quotaUser);
    }

    @Override
    public QueryNearFriends setUserIp(java.lang.String userIp) {
      return (QueryNearFriends) super.setUserIp(userIp);
    }

    @Override
    public QueryNearFriends set(String parameterName, Object value) {
      return (QueryNearFriends) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update_location".
   *
   * This request holds the parameters needed by the server_api server.  After setting any optional
   * parameters, call the {@link UpdateLocation#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.mythic_altar_759.server_api.model.ApiMessagesLocationRequestMessage}
   * @return the request
   */
  public UpdateLocation updateLocation(com.appspot.mythic_altar_759.server_api.model.ApiMessagesLocationRequestMessage content) throws java.io.IOException {
    UpdateLocation result = new UpdateLocation(content);
    initialize(result);
    return result;
  }

  public class UpdateLocation extends ServerApiRequest<Void> {

    private static final String REST_PATH = "location";

    /**
     * Create a request for the method "update_location".
     *
     * This request holds the parameters needed by the the server_api server.  After setting any
     * optional parameters, call the {@link UpdateLocation#execute()} method to invoke the remote
     * operation. <p> {@link UpdateLocation#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appspot.mythic_altar_759.server_api.model.ApiMessagesLocationRequestMessage}
     * @since 1.13
     */
    protected UpdateLocation(com.appspot.mythic_altar_759.server_api.model.ApiMessagesLocationRequestMessage content) {
      super(ServerApi.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public UpdateLocation setAlt(java.lang.String alt) {
      return (UpdateLocation) super.setAlt(alt);
    }

    @Override
    public UpdateLocation setFields(java.lang.String fields) {
      return (UpdateLocation) super.setFields(fields);
    }

    @Override
    public UpdateLocation setKey(java.lang.String key) {
      return (UpdateLocation) super.setKey(key);
    }

    @Override
    public UpdateLocation setOauthToken(java.lang.String oauthToken) {
      return (UpdateLocation) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateLocation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateLocation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateLocation setQuotaUser(java.lang.String quotaUser) {
      return (UpdateLocation) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateLocation setUserIp(java.lang.String userIp) {
      return (UpdateLocation) super.setUserIp(userIp);
    }

    @Override
    public UpdateLocation set(String parameterName, Object value) {
      return (UpdateLocation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update_settings".
   *
   * This request holds the parameters needed by the server_api server.  After setting any optional
   * parameters, call the {@link UpdateSettings#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.mythic_altar_759.server_api.model.ApiMessagesSettingsRequestMessage}
   * @return the request
   */
  public UpdateSettings updateSettings(com.appspot.mythic_altar_759.server_api.model.ApiMessagesSettingsRequestMessage content) throws java.io.IOException {
    UpdateSettings result = new UpdateSettings(content);
    initialize(result);
    return result;
  }

  public class UpdateSettings extends ServerApiRequest<Void> {

    private static final String REST_PATH = "settings";

    /**
     * Create a request for the method "update_settings".
     *
     * This request holds the parameters needed by the the server_api server.  After setting any
     * optional parameters, call the {@link UpdateSettings#execute()} method to invoke the remote
     * operation. <p> {@link UpdateSettings#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appspot.mythic_altar_759.server_api.model.ApiMessagesSettingsRequestMessage}
     * @since 1.13
     */
    protected UpdateSettings(com.appspot.mythic_altar_759.server_api.model.ApiMessagesSettingsRequestMessage content) {
      super(ServerApi.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public UpdateSettings setAlt(java.lang.String alt) {
      return (UpdateSettings) super.setAlt(alt);
    }

    @Override
    public UpdateSettings setFields(java.lang.String fields) {
      return (UpdateSettings) super.setFields(fields);
    }

    @Override
    public UpdateSettings setKey(java.lang.String key) {
      return (UpdateSettings) super.setKey(key);
    }

    @Override
    public UpdateSettings setOauthToken(java.lang.String oauthToken) {
      return (UpdateSettings) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSettings setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSettings) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSettings setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSettings) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSettings setUserIp(java.lang.String userIp) {
      return (UpdateSettings) super.setUserIp(userIp);
    }

    @Override
    public UpdateSettings set(String parameterName, Object value) {
      return (UpdateSettings) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link ServerApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link ServerApi}. */
    @Override
    public ServerApi build() {
      return new ServerApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ServerApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setServerApiRequestInitializer(
        ServerApiRequestInitializer serverapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(serverapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
